import { WeaponSpec, WeaponCategory } from './types';

function generateSprayPattern(
  shots: number,
  verticalClimb: number,
  horizontalSway: number,
  seed: number
): Array<[number, number]> {
  const pattern: Array<[number, number]> = [];
  for (let i = 0; i < shots; i++) {
    const progress = i / Math.max(1, shots - 1);
    // Initial vertical climb, then horizontal T/S curve like classic tactical rifles
    const pitch =
      i < 8
        ? verticalClimb * (0.85 + i * 0.06)
        : i < 16
        ? verticalClimb * 0.45
        : verticalClimb * 0.15;
    const phase = Math.sin((i - 5) * 0.45 + seed);
    const yaw = i < 4 ? horizontalSway * 0.15 * (i % 2 === 0 ? 1 : -1) : horizontalSway * phase * (0.6 + progress * 0.5);
    pattern.push([Number(pitch.toFixed(4)), Number(yaw.toFixed(4))]);
  }
  return pattern;
}

export const WEAPON_SPECS: Record<string, WeaponSpec> = {
  // =========================================================================
  // PISTOLS
  // =========================================================================
  vp9_tactical: {
    id: 'vp9_tactical',
    name: 'VP-9 Tactical',
    code: 'VP9-S',
    category: 'Pistols',
    slot: 'secondary',
    team: 'SENTINEL',
    price: 200,
    killReward: 300,
    damage: 35,
    range: 120,
    rangeModifier: 0.91,
    armorPenetration: 0.51,
    wallPenetration: 100,
    fireRateRpm: 352,
    automatic: false,
    magazineSize: 12,
    reserveAmmo: 36,
    reloadTimeSec: 2.1,
    moveSpeedMultiplier: 0.96,
    accuracyStanding: 0.0045,
    accuracyCrouching: 0.0032,
    accuracyMoving: 0.018,
    accuracyJumping: 0.085,
    recoilVertical: 0.018,
    recoilHorizontal: 0.006,
    recoilRecoveryRate: 9.5,
    recoilPattern: generateSprayPattern(12, 0.018, 0.006, 1),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    suppressed: true,
    tracerFrequency: 0,
    description: 'Standard-issue Sentinel suppressed tactical sidearm. Crisp first-shot accuracy and silent signature.',
    accentColor: '#06b6d4'
  },
  kestrel_18: {
    id: 'kestrel_18',
    name: 'Kestrel-18',
    code: 'K18-A',
    category: 'Pistols',
    slot: 'secondary',
    team: 'VORTEX',
    price: 200,
    killReward: 300,
    damage: 30,
    range: 110,
    rangeModifier: 0.88,
    armorPenetration: 0.47,
    wallPenetration: 90,
    fireRateRpm: 400,
    automatic: false,
    magazineSize: 20,
    reserveAmmo: 120,
    reloadTimeSec: 2.2,
    moveSpeedMultiplier: 0.96,
    accuracyStanding: 0.0055,
    accuracyCrouching: 0.004,
    accuracyMoving: 0.014,
    accuracyJumping: 0.075,
    recoilVertical: 0.015,
    recoilHorizontal: 0.007,
    recoilRecoveryRate: 10.0,
    recoilPattern: generateSprayPattern(20, 0.015, 0.007, 2),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'High-capacity polymer frame pistol favored by Vortex assault squads for mobile close-range pressure.',
    accentColor: '#f59e0b'
  },
  viper_p250: {
    id: 'viper_p250',
    name: 'Viper-P250',
    code: 'VP250',
    category: 'Pistols',
    slot: 'secondary',
    team: 'BOTH',
    price: 300,
    killReward: 300,
    damage: 38,
    range: 125,
    rangeModifier: 0.9,
    armorPenetration: 0.64,
    wallPenetration: 115,
    fireRateRpm: 400,
    automatic: false,
    magazineSize: 13,
    reserveAmmo: 26,
    reloadTimeSec: 2.2,
    moveSpeedMultiplier: 0.96,
    accuracyStanding: 0.006,
    accuracyCrouching: 0.0042,
    accuracyMoving: 0.02,
    accuracyJumping: 0.09,
    recoilVertical: 0.021,
    recoilHorizontal: 0.008,
    recoilRecoveryRate: 9.0,
    recoilPattern: generateSprayPattern(13, 0.021, 0.008, 3),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'Cost-effective armor-piercing pistol designed to threaten fully armored opponents on eco rounds.',
    accentColor: '#10b981'
  },
  spectre_auto: {
    id: 'spectre_auto',
    name: 'Spectre-Auto',
    code: 'SPC-75',
    category: 'Pistols',
    slot: 'secondary',
    team: 'BOTH',
    price: 500,
    killReward: 300,
    damage: 31,
    range: 105,
    rangeModifier: 0.86,
    armorPenetration: 0.77,
    wallPenetration: 110,
    fireRateRpm: 600,
    automatic: true,
    magazineSize: 12,
    reserveAmmo: 24,
    reloadTimeSec: 2.6,
    moveSpeedMultiplier: 0.95,
    accuracyStanding: 0.0085,
    accuracyCrouching: 0.006,
    accuracyMoving: 0.024,
    accuracyJumping: 0.1,
    recoilVertical: 0.025,
    recoilHorizontal: 0.014,
    recoilRecoveryRate: 8.5,
    recoilPattern: generateSprayPattern(12, 0.025, 0.014, 4),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 1,
    description: 'Compact full-auto machine pistol with blistering close-quarters output and limited reserve ammunition.',
    accentColor: '#a855f7'
  },
  talon_50: {
    id: 'talon_50',
    name: 'Talon .50 Heavy',
    code: 'TLN-50',
    category: 'Pistols',
    slot: 'secondary',
    team: 'BOTH',
    price: 700,
    killReward: 300,
    damage: 63,
    range: 160,
    rangeModifier: 0.85,
    armorPenetration: 0.93,
    wallPenetration: 200,
    fireRateRpm: 267,
    automatic: false,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadTimeSec: 2.2,
    moveSpeedMultiplier: 0.92,
    accuracyStanding: 0.0035,
    accuracyCrouching: 0.0024,
    accuracyMoving: 0.048,
    accuracyJumping: 0.16,
    recoilVertical: 0.055,
    recoilHorizontal: 0.018,
    recoilRecoveryRate: 4.8,
    recoilPattern: generateSprayPattern(7, 0.055, 0.018, 5),
    headMultiplier: 3.9,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 1,
    description: 'High-caliber hand cannon capable of one-shot headshots through ballistic helmets at medium range.',
    accentColor: '#ef4444'
  },

  // =========================================================================
  // SMGs
  // =========================================================================
  vector_9: {
    id: 'vector_9',
    name: 'Vector-9',
    code: 'VEC-9',
    category: 'SMGs',
    slot: 'primary',
    team: 'BOTH',
    price: 1250,
    killReward: 600,
    damage: 29,
    range: 110,
    rangeModifier: 0.84,
    armorPenetration: 0.48,
    wallPenetration: 90,
    fireRateRpm: 800,
    automatic: true,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTimeSec: 2.4,
    moveSpeedMultiplier: 0.96,
    accuracyStanding: 0.011,
    accuracyCrouching: 0.008,
    accuracyMoving: 0.018,
    accuracyJumping: 0.065,
    recoilVertical: 0.018,
    recoilHorizontal: 0.012,
    recoilRecoveryRate: 11.0,
    recoilPattern: generateSprayPattern(30, 0.018, 0.012, 6),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'Ultra-lightweight submachine gun with exceptional run-and-gun accuracy and $600 anti-eco kill reward.',
    accentColor: '#38bdf8'
  },
  stinger_45: {
    id: 'stinger_45',
    name: 'Stinger-45',
    code: 'STG-45',
    category: 'SMGs',
    slot: 'primary',
    team: 'BOTH',
    price: 1200,
    killReward: 600,
    damage: 35,
    range: 115,
    rangeModifier: 0.82,
    armorPenetration: 0.65,
    wallPenetration: 110,
    fireRateRpm: 666,
    automatic: true,
    magazineSize: 25,
    reserveAmmo: 100,
    reloadTimeSec: 2.8,
    moveSpeedMultiplier: 0.92,
    accuracyStanding: 0.01,
    accuracyCrouching: 0.007,
    accuracyMoving: 0.022,
    accuracyJumping: 0.08,
    recoilVertical: 0.022,
    recoilHorizontal: 0.011,
    recoilRecoveryRate: 9.5,
    recoilPattern: generateSprayPattern(25, 0.022, 0.011, 7),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'Hard-hitting .45 ACP submachine gun bridging the gap between SMGs and entry carbines.',
    accentColor: '#f97316'
  },
  mp_phantom: {
    id: 'mp_phantom',
    name: 'MP-Phantom SD',
    code: 'MPP-SD',
    category: 'SMGs',
    slot: 'primary',
    team: 'BOTH',
    price: 1500,
    killReward: 600,
    damage: 27,
    range: 120,
    rangeModifier: 0.87,
    armorPenetration: 0.62,
    wallPenetration: 100,
    fireRateRpm: 750,
    automatic: true,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTimeSec: 2.5,
    moveSpeedMultiplier: 0.94,
    accuracyStanding: 0.0085,
    accuracyCrouching: 0.006,
    accuracyMoving: 0.016,
    accuracyJumping: 0.075,
    recoilVertical: 0.016,
    recoilHorizontal: 0.009,
    recoilRecoveryRate: 11.5,
    recoilPattern: generateSprayPattern(30, 0.016, 0.009, 8),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    suppressed: true,
    tracerFrequency: 0,
    description: 'Integrally suppressed tactical SMG with zero tracer signature for flanking through smoke.',
    accentColor: '#06b6d4'
  },
  cyclone_p90: {
    id: 'cyclone_p90',
    name: 'Cyclone-P90',
    code: 'CYC-90',
    category: 'SMGs',
    slot: 'primary',
    team: 'BOTH',
    price: 2350,
    killReward: 300,
    damage: 26,
    range: 125,
    rangeModifier: 0.86,
    armorPenetration: 0.69,
    wallPenetration: 110,
    fireRateRpm: 857,
    automatic: true,
    magazineSize: 50,
    reserveAmmo: 100,
    reloadTimeSec: 3.1,
    moveSpeedMultiplier: 0.92,
    accuracyStanding: 0.011,
    accuracyCrouching: 0.008,
    accuracyMoving: 0.019,
    accuracyJumping: 0.085,
    recoilVertical: 0.019,
    recoilHorizontal: 0.014,
    recoilRecoveryRate: 10.5,
    recoilPattern: generateSprayPattern(50, 0.019, 0.014, 9),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: '50-round bullpup PDW built for relentless multi-target site entry and anti-rush suppression.',
    accentColor: '#eab308'
  },

  // =========================================================================
  // SHOTGUNS
  // =========================================================================
  breacher_12: {
    id: 'breacher_12',
    name: 'Breacher-12 Pump',
    code: 'BRC-12',
    category: 'Shotguns',
    slot: 'primary',
    team: 'BOTH',
    price: 1300,
    killReward: 900,
    damage: 28,
    pellets: 8,
    range: 65,
    rangeModifier: 0.7,
    armorPenetration: 0.7,
    wallPenetration: 60,
    fireRateRpm: 72,
    automatic: false,
    magazineSize: 8,
    reserveAmmo: 32,
    reloadTimeSec: 3.2,
    moveSpeedMultiplier: 0.9,
    accuracyStanding: 0.036,
    accuracyCrouching: 0.032,
    accuracyMoving: 0.042,
    accuracyJumping: 0.06,
    recoilVertical: 0.06,
    recoilHorizontal: 0.015,
    recoilRecoveryRate: 5.5,
    recoilPattern: generateSprayPattern(8, 0.06, 0.015, 10),
    headMultiplier: 3.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.15,
    legMultiplier: 0.8,
    tracerFrequency: 1,
    description: 'Heavy 12-gauge tactical pump shotgun firing 8 high-impact pellets with a $900 kill reward.',
    accentColor: '#f43f5e'
  },
  apex_auto8: {
    id: 'apex_auto8',
    name: 'Apex-Auto8',
    code: 'APX-8',
    category: 'Shotguns',
    slot: 'primary',
    team: 'BOTH',
    price: 2000,
    killReward: 900,
    damage: 21,
    pellets: 7,
    range: 60,
    rangeModifier: 0.68,
    armorPenetration: 0.75,
    wallPenetration: 70,
    fireRateRpm: 240,
    automatic: true,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadTimeSec: 2.9,
    moveSpeedMultiplier: 0.88,
    accuracyStanding: 0.042,
    accuracyCrouching: 0.036,
    accuracyMoving: 0.05,
    accuracyJumping: 0.075,
    recoilVertical: 0.042,
    recoilHorizontal: 0.016,
    recoilRecoveryRate: 6.5,
    recoilPattern: generateSprayPattern(7, 0.042, 0.016, 11),
    headMultiplier: 3.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.15,
    legMultiplier: 0.8,
    tracerFrequency: 1,
    description: 'Gas-operated semi-automatic combat shotgun capable of clearing tight choke points in seconds.',
    accentColor: '#fb7185'
  },

  // =========================================================================
  // MACHINE GUNS
  // =========================================================================
  titan_lmg: {
    id: 'titan_lmg',
    name: 'Titan-LMG',
    code: 'TTN-100',
    category: 'MachineGuns',
    slot: 'primary',
    team: 'BOTH',
    price: 1700,
    killReward: 300,
    damage: 35,
    range: 150,
    rangeModifier: 0.91,
    armorPenetration: 0.71,
    wallPenetration: 195,
    fireRateRpm: 800,
    automatic: true,
    magazineSize: 100,
    reserveAmmo: 200,
    reloadTimeSec: 5.2,
    moveSpeedMultiplier: 0.76,
    accuracyStanding: 0.016,
    accuracyCrouching: 0.009,
    accuracyMoving: 0.045,
    accuracyJumping: 0.14,
    recoilVertical: 0.02,
    recoilHorizontal: 0.01,
    recoilRecoveryRate: 8.0,
    recoilPattern: generateSprayPattern(100, 0.02, 0.01, 12),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 1,
    description: 'Belt-fed 100-round suppressive machine gun that stabilizes into a laser beam during sustained fire.',
    accentColor: '#f59e0b'
  },
  aegis_m249: {
    id: 'aegis_m249',
    name: 'Aegis-M249 SAW',
    code: 'AGS-249',
    category: 'MachineGuns',
    slot: 'primary',
    team: 'BOTH',
    price: 5200,
    killReward: 300,
    damage: 33,
    range: 165,
    rangeModifier: 0.94,
    armorPenetration: 0.8,
    wallPenetration: 210,
    fireRateRpm: 750,
    automatic: true,
    magazineSize: 100,
    reserveAmmo: 200,
    reloadTimeSec: 5.5,
    moveSpeedMultiplier: 0.78,
    accuracyStanding: 0.009,
    accuracyCrouching: 0.006,
    accuracyMoving: 0.038,
    accuracyJumping: 0.13,
    recoilVertical: 0.024,
    recoilHorizontal: 0.012,
    recoilRecoveryRate: 7.5,
    recoilPattern: generateSprayPattern(100, 0.024, 0.012, 13),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 1,
    description: 'Heavy squad automatic weapon with high armor penetration and lethal wallbang power.',
    accentColor: '#eab308'
  },

  // =========================================================================
  // RIFLES
  // =========================================================================
  korsak_gal: {
    id: 'korsak_gal',
    name: 'Korsak-GAL',
    code: 'KRS-556',
    category: 'Rifles',
    slot: 'primary',
    team: 'VORTEX',
    price: 1800,
    killReward: 300,
    damage: 30,
    range: 160,
    rangeModifier: 0.94,
    armorPenetration: 0.77,
    wallPenetration: 180,
    fireRateRpm: 666,
    automatic: true,
    magazineSize: 35,
    reserveAmmo: 90,
    reloadTimeSec: 2.9,
    moveSpeedMultiplier: 0.86,
    accuracyStanding: 0.0052,
    accuracyCrouching: 0.0038,
    accuracyMoving: 0.034,
    accuracyJumping: 0.11,
    recoilVertical: 0.024,
    recoilHorizontal: 0.013,
    recoilRecoveryRate: 8.5,
    recoilPattern: generateSprayPattern(35, 0.024, 0.013, 14),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'Rugged 35-round force-buy assault rifle for Vortex operatives on tight economy rounds.',
    accentColor: '#f97316'
  },
  dagger_fam: {
    id: 'dagger_fam',
    name: 'Dagger-FAM',
    code: 'DGR-25',
    category: 'Rifles',
    slot: 'primary',
    team: 'SENTINEL',
    price: 2050,
    killReward: 300,
    damage: 30,
    range: 160,
    rangeModifier: 0.94,
    armorPenetration: 0.7,
    wallPenetration: 175,
    fireRateRpm: 666,
    automatic: true,
    magazineSize: 25,
    reserveAmmo: 90,
    reloadTimeSec: 3.1,
    moveSpeedMultiplier: 0.88,
    accuracyStanding: 0.0048,
    accuracyCrouching: 0.0034,
    accuracyMoving: 0.032,
    accuracyJumping: 0.11,
    recoilVertical: 0.022,
    recoilHorizontal: 0.012,
    recoilRecoveryRate: 9.0,
    recoilPattern: generateSprayPattern(25, 0.022, 0.012, 15),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'Compact Sentinel bullpup service rifle engineered for budget defensive holds.',
    accentColor: '#38bdf8'
  },
  harbinger_47: {
    id: 'harbinger_47',
    name: 'Harbinger-47',
    code: 'HBG-47',
    category: 'Rifles',
    slot: 'primary',
    team: 'VORTEX',
    price: 2700,
    killReward: 300,
    damage: 36,
    range: 185,
    rangeModifier: 0.98,
    armorPenetration: 0.78,
    wallPenetration: 200,
    fireRateRpm: 600,
    automatic: true,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTimeSec: 2.4,
    moveSpeedMultiplier: 0.86,
    accuracyStanding: 0.0034,
    accuracyCrouching: 0.0024,
    accuracyMoving: 0.044,
    accuracyJumping: 0.13,
    recoilVertical: 0.031,
    recoilHorizontal: 0.016,
    recoilRecoveryRate: 7.5,
    recoilPattern: generateSprayPattern(30, 0.031, 0.016, 16),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'Signature heavy assault rifle of Vortex forces. Delivers a guaranteed 1-tap headshot against helmeted opponents.',
    accentColor: '#f59e0b'
  },
  vanguard_m4s: {
    id: 'vanguard_m4s',
    name: 'Vanguard-M4S',
    code: 'VGD-M4S',
    category: 'Rifles',
    slot: 'primary',
    team: 'SENTINEL',
    price: 2900,
    killReward: 300,
    damage: 38,
    range: 180,
    rangeModifier: 0.94,
    armorPenetration: 0.7,
    wallPenetration: 190,
    fireRateRpm: 600,
    automatic: true,
    magazineSize: 20,
    reserveAmmo: 80,
    reloadTimeSec: 2.8,
    moveSpeedMultiplier: 0.9,
    accuracyStanding: 0.0026,
    accuracyCrouching: 0.0018,
    accuracyMoving: 0.034,
    accuracyJumping: 0.11,
    recoilVertical: 0.02,
    recoilHorizontal: 0.009,
    recoilRecoveryRate: 9.5,
    recoilPattern: generateSprayPattern(20, 0.02, 0.009, 17),
    headMultiplier: 3.5,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    suppressed: true,
    tracerFrequency: 0,
    description: 'Suppressed Sentinel carbine with laser-tight recoil control, muffled acoustics, and zero bullet tracers.',
    accentColor: '#06b6d4'
  },
  vanguard_m4a: {
    id: 'vanguard_m4a',
    name: 'Vanguard-M4A',
    code: 'VGD-M4A',
    category: 'Rifles',
    slot: 'primary',
    team: 'SENTINEL',
    price: 3000,
    killReward: 300,
    damage: 33,
    range: 180,
    rangeModifier: 0.97,
    armorPenetration: 0.7,
    wallPenetration: 195,
    fireRateRpm: 666,
    automatic: true,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTimeSec: 3.0,
    moveSpeedMultiplier: 0.9,
    accuracyStanding: 0.003,
    accuracyCrouching: 0.0021,
    accuracyMoving: 0.038,
    accuracyJumping: 0.12,
    recoilVertical: 0.024,
    recoilHorizontal: 0.011,
    recoilRecoveryRate: 8.8,
    recoilPattern: generateSprayPattern(30, 0.024, 0.011, 18),
    headMultiplier: 3.9,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    tracerFrequency: 2,
    description: 'Unsuppressed 30-round Sentinel assault rifle with a fast 666 RPM fire rate for anchoring bomb sites.',
    accentColor: '#0ea5e9'
  },
  solaris_553: {
    id: 'solaris_553',
    name: 'Solaris-553 Scoped',
    code: 'SLR-553',
    category: 'Rifles',
    slot: 'primary',
    team: 'VORTEX',
    price: 3000,
    killReward: 300,
    damage: 30,
    range: 195,
    rangeModifier: 0.98,
    armorPenetration: 1.0,
    wallPenetration: 200,
    fireRateRpm: 545,
    automatic: true,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTimeSec: 2.8,
    moveSpeedMultiplier: 0.84,
    accuracyStanding: 0.0025,
    accuracyCrouching: 0.0018,
    accuracyMoving: 0.042,
    accuracyJumping: 0.13,
    accuracyScoped: 0.0011,
    recoilVertical: 0.027,
    recoilHorizontal: 0.015,
    recoilRecoveryRate: 8.0,
    recoilPattern: generateSprayPattern(30, 0.027, 0.015, 19),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    scopeLevels: [45],
    tracerFrequency: 2,
    description: '100% armor-penetrating Vortex rifle equipped with a 1.5x precision ACOG optic.',
    accentColor: '#ea580c'
  },
  falcon_aug: {
    id: 'falcon_aug',
    name: 'Falcon-AUG Scoped',
    code: 'FLC-AUG',
    category: 'Rifles',
    slot: 'primary',
    team: 'SENTINEL',
    price: 3300,
    killReward: 300,
    damage: 28,
    range: 195,
    rangeModifier: 0.98,
    armorPenetration: 0.9,
    wallPenetration: 200,
    fireRateRpm: 600,
    automatic: true,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTimeSec: 3.4,
    moveSpeedMultiplier: 0.88,
    accuracyStanding: 0.0026,
    accuracyCrouching: 0.0018,
    accuracyMoving: 0.039,
    accuracyJumping: 0.12,
    accuracyScoped: 0.001,
    recoilVertical: 0.023,
    recoilHorizontal: 0.012,
    recoilRecoveryRate: 8.6,
    recoilPattern: generateSprayPattern(30, 0.023, 0.012, 20),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    scopeLevels: [45],
    tracerFrequency: 2,
    description: 'Scoped Sentinel bullpup rifle delivering pinpoint accuracy down long defensive sightlines.',
    accentColor: '#22d3ee'
  },

  // =========================================================================
  // SNIPER RIFLES
  // =========================================================================
  scout_ssr: {
    id: 'scout_ssr',
    name: 'Scout-SSR Bolt',
    code: 'SCT-08',
    category: 'Snipers',
    slot: 'primary',
    team: 'BOTH',
    price: 1700,
    killReward: 300,
    damage: 88,
    range: 260,
    rangeModifier: 0.98,
    armorPenetration: 0.85,
    wallPenetration: 240,
    fireRateRpm: 48,
    automatic: false,
    magazineSize: 10,
    reserveAmmo: 90,
    reloadTimeSec: 2.9,
    moveSpeedMultiplier: 0.92,
    accuracyStanding: 0.025,
    accuracyCrouching: 0.018,
    accuracyMoving: 0.055,
    accuracyJumping: 0.022,
    accuracyScoped: 0.0005,
    recoilVertical: 0.055,
    recoilHorizontal: 0.008,
    recoilRecoveryRate: 6.0,
    recoilPattern: [[0.055, 0]],
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    scopeLevels: [35, 14],
    tracerFrequency: 1,
    description: 'Lightweight carbon-fiber bolt-action sniper rifle with high mobility and lethal headshot potential.',
    accentColor: '#10b981'
  },
  monolith_awm: {
    id: 'monolith_awm',
    name: 'Monolith-AWM .338',
    code: 'MNL-338',
    category: 'Snipers',
    slot: 'primary',
    team: 'BOTH',
    price: 4750,
    killReward: 100,
    damage: 115,
    range: 300,
    rangeModifier: 0.99,
    armorPenetration: 0.975,
    wallPenetration: 280,
    fireRateRpm: 41,
    automatic: false,
    magazineSize: 5,
    reserveAmmo: 30,
    reloadTimeSec: 3.6,
    moveSpeedMultiplier: 0.8,
    accuracyStanding: 0.065,
    accuracyCrouching: 0.048,
    accuracyMoving: 0.14,
    accuracyJumping: 0.22,
    accuracyScoped: 0.0002,
    recoilVertical: 0.09,
    recoilHorizontal: 0.012,
    recoilRecoveryRate: 4.0,
    recoilPattern: [[0.09, 0]],
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.74,
    scopeLevels: [35, 12],
    tracerFrequency: 1,
    description: 'High-risk, high-reward .338 Lapua Magnum sniper rifle. Instant one-shot elimination on head or torso hits.',
    accentColor: '#ef4444'
  },
  archon_dmr: {
    id: 'archon_dmr',
    name: 'Archon-DMR Auto',
    code: 'ARC-20',
    category: 'Snipers',
    slot: 'primary',
    team: 'BOTH',
    price: 5000,
    killReward: 300,
    damage: 80,
    range: 280,
    rangeModifier: 0.98,
    armorPenetration: 0.825,
    wallPenetration: 250,
    fireRateRpm: 240,
    automatic: true,
    magazineSize: 20,
    reserveAmmo: 90,
    reloadTimeSec: 3.3,
    moveSpeedMultiplier: 0.84,
    accuracyStanding: 0.038,
    accuracyCrouching: 0.025,
    accuracyMoving: 0.09,
    accuracyJumping: 0.18,
    accuracyScoped: 0.0008,
    recoilVertical: 0.042,
    recoilHorizontal: 0.012,
    recoilRecoveryRate: 6.5,
    recoilPattern: generateSprayPattern(20, 0.042, 0.012, 21),
    headMultiplier: 4.0,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.25,
    legMultiplier: 0.75,
    scopeLevels: [35, 14],
    tracerFrequency: 1,
    description: 'Semi-automatic marksman sniper capable of rapid two-shot body eliminations down long corridors.',
    accentColor: '#a855f7'
  },

  // =========================================================================
  // MELEE
  // =========================================================================
  combat_blade: {
    id: 'combat_blade',
    name: 'Karambit MK-IV',
    code: 'KRM-4',
    category: 'Melee',
    slot: 'melee',
    team: 'BOTH',
    price: 0,
    killReward: 1500,
    damage: 55,
    range: 2.8,
    rangeModifier: 1.0,
    armorPenetration: 0.85,
    wallPenetration: 0,
    fireRateRpm: 150,
    automatic: false,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTimeSec: 0,
    moveSpeedMultiplier: 1.0,
    accuracyStanding: 0,
    accuracyCrouching: 0,
    accuracyMoving: 0,
    accuracyJumping: 0,
    recoilVertical: 0,
    recoilHorizontal: 0,
    recoilRecoveryRate: 10,
    recoilPattern: [[0, 0]],
    headMultiplier: 1.5,
    chestMultiplier: 1.0,
    stomachMultiplier: 1.0,
    legMultiplier: 1.0,
    tracerFrequency: 0,
    description: 'Titanium tactical blade granting maximum 250 u/s movement speed and $1500 elimination bounty.',
    accentColor: '#38bdf8'
  },

  // =========================================================================
  // GRENADES
  // =========================================================================
  smoke_grenade: {
    id: 'smoke_grenade',
    name: 'Smoke Canister',
    code: 'SMK-G',
    category: 'Grenades',
    slot: 'grenade',
    team: 'BOTH',
    price: 300,
    killReward: 300,
    damage: 0,
    range: 45,
    rangeModifier: 1,
    armorPenetration: 1,
    wallPenetration: 0,
    fireRateRpm: 60,
    automatic: false,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTimeSec: 0.8,
    moveSpeedMultiplier: 0.98,
    accuracyStanding: 0,
    accuracyCrouching: 0,
    accuracyMoving: 0,
    accuracyJumping: 0,
    recoilVertical: 0,
    recoilHorizontal: 0,
    recoilRecoveryRate: 10,
    recoilPattern: [[0, 0]],
    headMultiplier: 1,
    chestMultiplier: 1,
    stomachMultiplier: 1,
    legMultiplier: 1,
    tracerFrequency: 0,
    grenadeType: 'smoke',
    description: 'Deploys a dense volumetric aerosol cloud for 18 seconds that blocks sightlines and AI vision.',
    accentColor: '#94a3b8'
  },
  flash_grenade: {
    id: 'flash_grenade',
    name: 'Flashbang Charge',
    code: 'FLS-G',
    category: 'Grenades',
    slot: 'grenade',
    team: 'BOTH',
    price: 200,
    killReward: 300,
    damage: 1,
    range: 45,
    rangeModifier: 1,
    armorPenetration: 1,
    wallPenetration: 0,
    fireRateRpm: 60,
    automatic: false,
    magazineSize: 1,
    reserveAmmo: 1,
    reloadTimeSec: 0.8,
    moveSpeedMultiplier: 0.98,
    accuracyStanding: 0,
    accuracyCrouching: 0,
    accuracyMoving: 0,
    accuracyJumping: 0,
    recoilVertical: 0,
    recoilHorizontal: 0,
    recoilRecoveryRate: 10,
    recoilPattern: [[0, 0]],
    headMultiplier: 1,
    chestMultiplier: 1,
    stomachMultiplier: 1,
    legMultiplier: 1,
    tracerFrequency: 0,
    grenadeType: 'flash',
    description: 'Concussive photonic charge that blinds and deafens anyone looking toward the detonation.',
    accentColor: '#fef08a'
  },
  he_grenade: {
    id: 'he_grenade',
    name: 'HE-X Frag Grenade',
    code: 'HEX-G',
    category: 'Grenades',
    slot: 'grenade',
    team: 'BOTH',
    price: 300,
    killReward: 300,
    damage: 98,
    range: 45,
    rangeModifier: 1,
    armorPenetration: 0.6,
    wallPenetration: 0,
    fireRateRpm: 60,
    automatic: false,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTimeSec: 0.8,
    moveSpeedMultiplier: 0.98,
    accuracyStanding: 0,
    accuracyCrouching: 0,
    accuracyMoving: 0,
    accuracyJumping: 0,
    recoilVertical: 0,
    recoilHorizontal: 0,
    recoilRecoveryRate: 10,
    recoilPattern: [[0, 0]],
    headMultiplier: 1,
    chestMultiplier: 1,
    stomachMultiplier: 1,
    legMultiplier: 1,
    tracerFrequency: 0,
    grenadeType: 'he',
    description: 'High-explosive fragmentation grenade dealing lethal blast damage within a 7-meter radius.',
    accentColor: '#ef4444'
  },
  incendiary_grenade: {
    id: 'incendiary_grenade',
    name: 'Thermite Incendiary',
    code: 'THM-G',
    category: 'Grenades',
    slot: 'grenade',
    team: 'BOTH',
    price: 500,
    killReward: 300,
    damage: 40,
    range: 45,
    rangeModifier: 1,
    armorPenetration: 0.9,
    wallPenetration: 0,
    fireRateRpm: 60,
    automatic: false,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTimeSec: 0.8,
    moveSpeedMultiplier: 0.98,
    accuracyStanding: 0,
    accuracyCrouching: 0,
    accuracyMoving: 0,
    accuracyJumping: 0,
    recoilVertical: 0,
    recoilHorizontal: 0,
    recoilRecoveryRate: 10,
    recoilPattern: [[0, 0]],
    headMultiplier: 1,
    chestMultiplier: 1,
    stomachMultiplier: 1,
    legMultiplier: 1,
    tracerFrequency: 0,
    grenadeType: 'incendiary',
    description: 'Ignites a 4.5-meter area-denial fire patch on impact for 7 seconds.',
    accentColor: '#f97316'
  },
  decoy_grenade: {
    id: 'decoy_grenade',
    name: 'Acoustic Decoy',
    code: 'DCY-G',
    category: 'Grenades',
    slot: 'grenade',
    team: 'BOTH',
    price: 50,
    killReward: 300,
    damage: 5,
    range: 45,
    rangeModifier: 1,
    armorPenetration: 0.5,
    wallPenetration: 0,
    fireRateRpm: 60,
    automatic: false,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTimeSec: 0.8,
    moveSpeedMultiplier: 0.98,
    accuracyStanding: 0,
    accuracyCrouching: 0,
    accuracyMoving: 0,
    accuracyJumping: 0,
    recoilVertical: 0,
    recoilHorizontal: 0,
    recoilRecoveryRate: 10,
    recoilPattern: [[0, 0]],
    headMultiplier: 1,
    chestMultiplier: 1,
    stomachMultiplier: 1,
    legMultiplier: 1,
    tracerFrequency: 0,
    grenadeType: 'decoy',
    description: 'Projects simulated weapon fire and a false radar signature for 15 seconds.',
    accentColor: '#38bdf8'
  }
};

export interface EquipmentSpec {
  id: string;
  name: string;
  code: string;
  price: number;
  team: 'SENTINEL' | 'VORTEX' | 'BOTH';
  description: string;
}

export const EQUIPMENT_SPECS: EquipmentSpec[] = [
  {
    id: 'kevlar_vest',
    name: 'Kevlar Ballistic Vest',
    code: 'EQ-VEST',
    price: 650,
    team: 'BOTH',
    description: 'Provides 100 torso and stomach armor points, reducing incoming aim-punch and bullet damage.'
  },
  {
    id: 'kevlar_helmet',
    name: 'Kevlar + Tactical Helmet',
    code: 'EQ-HELM',
    price: 1000,
    team: 'BOTH',
    description: 'Full 100 ballistic armor plus composite helmet protecting against sidearm/SMG one-shot headshots.'
  },
  {
    id: 'defuse_kit',
    name: 'Omni-Tool Defuse Kit',
    code: 'EQ-KIT',
    price: 400,
    team: 'SENTINEL',
    description: 'Cuts Pulse Bomb defusal duration in half from 10.0 seconds down to 5.0 seconds.'
  }
];

export interface HitCalculationInput {
  weapon: WeaponSpec;
  distanceMeters: number;
  hitGroup: 'head' | 'chest' | 'stomach' | 'leg';
  targetArmor: number;
  targetHasHelmet: boolean;
  wallPenetrationLoss?: number; // 0 to 0.9
}

export interface HitCalculationResult {
  healthDamage: number;
  armorDamage: number;
  isFatal: boolean;
}

export function calculateWeaponDamage(
  input: HitCalculationInput,
  currentTargetHealth = 100
): HitCalculationResult {
  const { weapon, distanceMeters, hitGroup, targetArmor, targetHasHelmet, wallPenetrationLoss = 0 } = input;

  // Distance falloff per 15 meters
  const falloffSegments = Math.max(0, distanceMeters / 15);
  const distanceFactor = Math.pow(weapon.rangeModifier, falloffSegments);

  // Hitbox multiplier
  let groupMult = weapon.chestMultiplier;
  if (hitGroup === 'head') groupMult = weapon.headMultiplier;
  else if (hitGroup === 'stomach') groupMult = weapon.stomachMultiplier;
  else if (hitGroup === 'leg') groupMult = weapon.legMultiplier;

  // Wallbang reduction
  const penetrationFactor = Math.max(0.1, 1 - wallPenetrationLoss);

  let rawDamage = weapon.damage * distanceFactor * groupMult * penetrationFactor;

  // Armor calculation (legs are unarmored; head requires helmet)
  const isArmoredHit =
    targetArmor > 0 &&
    hitGroup !== 'leg' &&
    (hitGroup !== 'head' || targetHasHelmet);

  let armorDamage = 0;
  if (isArmoredHit) {
    const absorbedByArmor = rawDamage * (1 - weapon.armorPenetration) * 0.5;
    armorDamage = Math.min(targetArmor, Math.ceil(absorbedByArmor));
    rawDamage = rawDamage * weapon.armorPenetration;
  }

  const healthDamage = Math.max(1, Math.round(rawDamage));
  return {
    healthDamage,
    armorDamage,
    isFatal: healthDamage >= currentTargetHealth
  };
}

export function getWeaponsByCategory(category: WeaponCategory, team?: 'SENTINEL' | 'VORTEX'): WeaponSpec[] {
  return Object.values(WEAPON_SPECS).filter(
    (w) => w.category === category && (!team || w.team === 'BOTH' || w.team === team)
  );
}
