import { GameMapDefinition, MapObjectDef } from '../../shared/types';

function createPerimeterWalls(width: number, depth: number, height: number, color = '#1e293b'): MapObjectDef[] {
  const hw = width / 2;
  const hd = depth / 2;
  const hh = height / 2;
  return [
    {
      id: 'ground_main',
      name: 'Main Ground Slab',
      type: 'floor',
      position: [0, -0.5, 0],
      size: [width, 1, depth],
      color: '#1e2530',
      material: 'concrete',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'global'
    },
    {
      id: 'wall_north',
      name: 'North Perimeter Wall',
      type: 'wall',
      position: [0, hh, -hd],
      size: [width, height, 1.5],
      color,
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'global',
      penetrationResistance: 1.0
    },
    {
      id: 'wall_south',
      name: 'South Perimeter Wall',
      type: 'wall',
      position: [0, hh, hd],
      size: [width, height, 1.5],
      color,
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'global',
      penetrationResistance: 1.0
    },
    {
      id: 'wall_west',
      name: 'West Perimeter Wall',
      type: 'wall',
      position: [-hw, hh, 0],
      size: [1.5, height, depth],
      color,
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'global',
      penetrationResistance: 1.0
    },
    {
      id: 'wall_east',
      name: 'East Perimeter Wall',
      type: 'wall',
      position: [hw, hh, 0],
      size: [1.5, height, depth],
      color,
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'global',
      penetrationResistance: 1.0
    }
  ];
}

export const HARBOR_PROTOCOL_MAP: GameMapDefinition = {
  id: 'harbor_protocol',
  name: 'Harbor Protocol',
  subtitle: 'Automated Maritime Logistics Terminal // Sector 04',
  author: 'Vanguard Studio',
  version: '2.4.0',
  description:
    'Three-lane competitive tactical map set in a fortified North Sea container port. Features Site A Container Yard, Mid Freight Corridor with elevated Catwalk, and Site B Turbine Warehouse.',
  supportedModes: ['Competitive', 'Premier', 'Wingman', 'Rush', 'Casual', 'Deathmatch', 'Retakes', 'Practice', 'Custom'],
  ambientColor: '#64748b',
  skyColor: '#0b1322',
  fogColor: '#131f33',
  sunDirection: [55, 95, 40],
  bounds: { min: [-65, -2, -65], max: [65, 25, 65] },
  objects: [
    ...createPerimeterWalls(110, 110, 10, '#273244'),

    // Spawns & Buy Zones
    {
      id: 'spawn_sentinel_1',
      name: 'Sentinel Spawn Primary',
      type: 'spawn_sentinel',
      position: [0, 0.1, -44],
      size: [14, 0.2, 8],
      color: '#06b6d4',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_s'
    },
    {
      id: 'buy_sentinel',
      name: 'Sentinel Buy Zone',
      type: 'buy_zone',
      position: [0, 1.5, -44],
      size: [18, 3, 12],
      color: '#06b6d4',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_s'
    },
    {
      id: 'spawn_vortex_1',
      name: 'Vortex Spawn Primary',
      type: 'spawn_vortex',
      position: [0, 0.1, 44],
      size: [14, 0.2, 8],
      color: '#f59e0b',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_v'
    },
    {
      id: 'buy_vortex',
      name: 'Vortex Buy Zone',
      type: 'buy_zone',
      position: [0, 1.5, 44],
      size: [18, 3, 12],
      color: '#f59e0b',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_v'
    },

    // Bomb Sites
    {
      id: 'site_a_zone',
      name: 'Bomb Site A (Container Dock)',
      type: 'bomb_site_a',
      position: [-30, 0.15, -18],
      size: [14, 0.3, 14],
      color: '#ef4444',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'site_a'
    },
    {
      id: 'site_b_zone',
      name: 'Bomb Site B (Turbine Hall)',
      type: 'bomb_site_b',
      position: [30, 0.15, -18],
      size: [14, 0.3, 14],
      color: '#f97316',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'site_b'
    },

    // Major Divider Walls (Occluders between Mid, Site A, Site B, and Spawns)
    {
      id: 'wall_mid_west_1',
      name: 'Mid West Divider North',
      type: 'wall',
      position: [-14, 3.5, -18],
      size: [1.5, 7, 24],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 0.85
    },
    {
      id: 'wall_mid_west_2',
      name: 'Mid West Divider South',
      type: 'wall',
      position: [-14, 3.5, 18],
      size: [1.5, 7, 24],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 0.85
    },
    {
      id: 'wall_mid_east_1',
      name: 'Mid East Divider North',
      type: 'wall',
      position: [14, 3.5, -18],
      size: [1.5, 7, 24],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 0.85
    },
    {
      id: 'wall_mid_east_2',
      name: 'Mid East Divider South',
      type: 'wall',
      position: [14, 3.5, 18],
      size: [1.5, 7, 24],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 0.85
    },

    // Mid Choke Blockers & Sniper Window
    {
      id: 'mid_center_block',
      name: 'Mid Freight Container',
      type: 'cube',
      position: [-3, 1.8, 0],
      size: [3.2, 3.6, 7.5],
      color: '#0284c7',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 0.65
    },
    {
      id: 'mid_catwalk_platform',
      name: 'Mid Elevated Catwalk',
      type: 'floor',
      position: [9.5, 2.4, 0],
      size: [4.5, 0.4, 22],
      color: '#475569',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'mid'
    },
    {
      id: 'mid_catwalk_ramp',
      name: 'Mid Catwalk South Ramp',
      type: 'ramp',
      position: [9.5, 1.2, 14],
      size: [4.2, 2.4, 6],
      color: '#64748b',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'mid'
    },
    {
      id: 'mid_catwalk_stairs',
      name: 'Mid Catwalk North Stairs',
      type: 'stairs',
      position: [9.5, 1.2, -14],
      size: [4.2, 2.4, 6],
      color: '#64748b',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'mid'
    },

    // Site A (Container Dock) Architecture & Cover
    {
      id: 'site_a_container_red',
      name: 'Site A Core Container',
      type: 'cube',
      position: [-30, 1.75, -18],
      size: [4.5, 3.5, 6.5],
      color: '#dc2626',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_a',
      penetrationResistance: 0.6
    },
    {
      id: 'site_a_crate_1',
      name: 'Site A Headshot Box',
      type: 'cover',
      position: [-23, 0.85, -12],
      size: [2.2, 1.7, 2.2],
      color: '#d97706',
      material: 'wood',
      collidable: true,
      occluder: false,
      lodTier: 'near',
      roomId: 'site_a',
      penetrationResistance: 0.25
    },
    {
      id: 'site_a_crate_2',
      name: 'Site A Double Stack',
      type: 'cover',
      position: [-38, 1.6, -24],
      size: [2.8, 3.2, 2.8],
      color: '#b45309',
      material: 'wood',
      collidable: true,
      occluder: true,
      lodTier: 'near',
      roomId: 'site_a',
      penetrationResistance: 0.3
    },
    {
      id: 'a_long_wall',
      name: 'A Long Partition Wall',
      type: 'wall',
      position: [-34, 3.5, 8],
      size: [14, 7, 1.5],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_a',
      penetrationResistance: 0.9
    },
    {
      id: 'a_heaven_plat',
      name: 'Site A Overwatch Platform',
      type: 'floor',
      position: [-30, 3.0, -32],
      size: [12, 0.5, 6],
      color: '#475569',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'site_a'
    },
    {
      id: 'a_heaven_ladder',
      name: 'Site A Overwatch Ladder',
      type: 'ladder',
      position: [-24.5, 1.5, -32],
      size: [1.0, 3.2, 1.0],
      color: '#f59e0b',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'near',
      roomId: 'site_a'
    },

    // Site B (Turbine Warehouse) Architecture & Cover
    {
      id: 'site_b_turbine_1',
      name: 'Site B Primary Generator',
      type: 'cylinder',
      position: [30, 2.0, -18],
      size: [4.2, 4.0, 4.2],
      color: '#0d9488',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_b',
      penetrationResistance: 0.75
    },
    {
      id: 'site_b_pillar_1',
      name: 'B Hall Support Pillar West',
      type: 'cube',
      position: [23, 3.5, -8],
      size: [2.5, 7, 2.5],
      color: '#475569',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_b',
      penetrationResistance: 0.9
    },
    {
      id: 'site_b_pillar_2',
      name: 'B Hall Support Pillar East',
      type: 'cube',
      position: [37, 3.5, -8],
      size: [2.5, 7, 2.5],
      color: '#475569',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_b',
      penetrationResistance: 0.9
    },
    {
      id: 'site_b_cover_box',
      name: 'B Default Plant Cover',
      type: 'cover',
      position: [34, 1.0, -23],
      size: [3.0, 2.0, 2.0],
      color: '#ca8a04',
      material: 'wood',
      collidable: true,
      occluder: false,
      lodTier: 'near',
      roomId: 'site_b',
      penetrationResistance: 0.25
    },
    {
      id: 'b_main_wall',
      name: 'B Main Choke Wall',
      type: 'wall',
      position: [36, 3.5, 10],
      size: [16, 7, 1.5],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_b',
      penetrationResistance: 0.9
    },
    {
      id: 'b_water_canal',
      name: 'B Lower Drainage Basin',
      type: 'water',
      position: [26, 0.08, 18],
      size: [10, 0.2, 10],
      color: '#0284c7',
      material: 'water',
      collidable: false,
      occluder: false,
      lodTier: 'medium',
      roomId: 'site_b'
    },

    // Decorative & Distant Streaming Props (Near / Medium / Far LOD tiers)
    {
      id: 'prop_crane_base_a',
      name: 'Harbor Gantry Strut A',
      type: 'prop',
      position: [-46, 5.0, -35],
      size: [2.0, 10.0, 2.0],
      color: '#f59e0b',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'far',
      roomId: 'site_a'
    },
    {
      id: 'prop_crane_base_b',
      name: 'Harbor Gantry Strut B',
      type: 'prop',
      position: [46, 5.0, -35],
      size: [2.0, 10.0, 2.0],
      color: '#06b6d4',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'far',
      roomId: 'site_b'
    },
    {
      id: 'prop_mid_barrels',
      name: 'Mid Industrial Drums',
      type: 'prop',
      position: [-10, 0.9, 5],
      size: [1.5, 1.8, 1.5],
      color: '#3b82f6',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'near',
      roomId: 'mid'
    },
    {
      id: 'prop_v_spawn_truck',
      name: 'Vortex Staging Transport',
      type: 'prop',
      position: [-12, 1.6, 38],
      size: [3.5, 3.2, 7.0],
      color: '#475569',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'medium',
      roomId: 'spawn_v'
    },
    {
      id: 'prop_s_spawn_apc',
      name: 'Sentinel Command Carrier',
      type: 'prop',
      position: [12, 1.6, -38],
      size: [3.5, 3.2, 7.0],
      color: '#1e3a8a',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'medium',
      roomId: 'spawn_s'
    }
  ],
  portals: [
    { id: 'portal_mid_to_a', fromRoom: 'mid', toRoom: 'site_a', position: [-14, 2, 0], size: [2, 4, 8] },
    { id: 'portal_mid_to_b', fromRoom: 'mid', toRoom: 'site_b', position: [14, 2, 0], size: [2, 4, 8] },
    { id: 'portal_s_to_a', fromRoom: 'spawn_s', toRoom: 'site_a', position: [-20, 2, -30], size: [8, 4, 2] },
    { id: 'portal_s_to_b', fromRoom: 'spawn_s', toRoom: 'site_b', position: [20, 2, -30], size: [8, 4, 2] },
    { id: 'portal_v_to_a', fromRoom: 'spawn_v', toRoom: 'site_a', position: [-20, 2, 28], size: [8, 4, 2] },
    { id: 'portal_v_to_b', fromRoom: 'spawn_v', toRoom: 'site_b', position: [20, 2, 28], size: [8, 4, 2] }
  ],
  waypoints: [
    { id: 'wp_s_spawn', position: [0, 0, -42], connections: ['wp_mid_north', 'wp_a_ct', 'wp_b_ct'], tag: 'sentinelSpawn' },
    { id: 'wp_v_spawn', position: [0, 0, 42], connections: ['wp_mid_south', 'wp_a_main', 'wp_b_main'], tag: 'vortexSpawn' },
    { id: 'wp_mid_south', position: [0, 0, 22], connections: ['wp_v_spawn', 'wp_mid_center'], tag: 'mid' },
    { id: 'wp_mid_center', position: [3, 0, 0], connections: ['wp_mid_south', 'wp_mid_north', 'wp_a_conn', 'wp_b_conn'], tag: 'mid' },
    { id: 'wp_mid_north', position: [0, 0, -22], connections: ['wp_mid_center', 'wp_s_spawn'], tag: 'mid' },
    { id: 'wp_a_main', position: [-24, 0, 22], connections: ['wp_v_spawn', 'wp_a_site'], tag: 'cover' },
    { id: 'wp_a_conn', position: [-14, 0, 0], connections: ['wp_mid_center', 'wp_a_site'], tag: 'cover' },
    { id: 'wp_a_site', position: [-28, 0, -16], connections: ['wp_a_main', 'wp_a_conn', 'wp_a_ct'], tag: 'siteA' },
    { id: 'wp_a_ct', position: [-20, 0, -34], connections: ['wp_a_site', 'wp_s_spawn'], tag: 'cover' },
    { id: 'wp_b_main', position: [24, 0, 22], connections: ['wp_v_spawn', 'wp_b_site'], tag: 'cover' },
    { id: 'wp_b_conn', position: [14, 0, 0], connections: ['wp_mid_center', 'wp_b_site'], tag: 'cover' },
    { id: 'wp_b_site', position: [28, 0, -16], connections: ['wp_b_main', 'wp_b_conn', 'wp_b_ct'], tag: 'siteB' },
    { id: 'wp_b_ct', position: [20, 0, -34], connections: ['wp_b_site', 'wp_s_spawn'], tag: 'cover' }
  ],
  callouts: [
    { name: 'Sentinel Plaza', position: [0, 0, -42], radius: 14 },
    { name: 'Vortex Staging', position: [0, 0, 42], radius: 14 },
    { name: 'Mid Freight', position: [0, 0, 0], radius: 14 },
    { name: 'Catwalk', position: [9.5, 2.4, 0], radius: 10 },
    { name: 'A Site (Dock)', position: [-30, 0, -18], radius: 14 },
    { name: 'A Long', position: [-28, 0, 18], radius: 12 },
    { name: 'B Site (Turbine)', position: [30, 0, -18], radius: 14 },
    { name: 'B Canal', position: [26, 0, 18], radius: 12 }
  ]
};

export const CITADEL_SPIRE_MAP: GameMapDefinition = {
  id: 'citadel_spire',
  name: 'Citadel Spire',
  subtitle: 'High-Altitude Quantum Data Citadel // Sector 09',
  author: 'Vanguard Studio',
  version: '1.8.0',
  description:
    'Brutalist concrete and brushed-titanium data fortress featuring long sniper corridors, dual-level courtyard transitions, and high-penetration server partitions.',
  supportedModes: ['Competitive', 'Premier', 'Rush', 'Casual', 'Deathmatch', 'Retakes', 'Practice', 'Custom'],
  ambientColor: '#64748b',
  skyColor: '#090d16',
  fogColor: '#111827',
  sunDirection: [-40, 90, 30],
  bounds: { min: [-60, -2, -60], max: [60, 25, 60] },
  objects: [
    ...createPerimeterWalls(104, 104, 10, '#1e293b'),
    {
      id: 'cit_spawn_s',
      name: 'Sentinel Spawn',
      type: 'spawn_sentinel',
      position: [0, 0.1, -42],
      size: [14, 0.2, 8],
      color: '#06b6d4',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_s'
    },
    {
      id: 'cit_buy_s',
      name: 'Sentinel Buy Zone',
      type: 'buy_zone',
      position: [0, 1.5, -42],
      size: [16, 3, 10],
      color: '#06b6d4',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_s'
    },
    {
      id: 'cit_spawn_v',
      name: 'Vortex Spawn',
      type: 'spawn_vortex',
      position: [0, 0.1, 42],
      size: [14, 0.2, 8],
      color: '#f59e0b',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_v'
    },
    {
      id: 'cit_buy_v',
      name: 'Vortex Buy Zone',
      type: 'buy_zone',
      position: [0, 1.5, 42],
      size: [16, 3, 10],
      color: '#f59e0b',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'spawn_v'
    },
    {
      id: 'cit_site_a',
      name: 'Bomb Site A (Server Core)',
      type: 'bomb_site_a',
      position: [-28, 0.15, -16],
      size: [13, 0.3, 13],
      color: '#ef4444',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'site_a'
    },
    {
      id: 'cit_site_b',
      name: 'Bomb Site B (Helipad Deck)',
      type: 'bomb_site_b',
      position: [28, 0.15, -16],
      size: [13, 0.3, 13],
      color: '#f97316',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'site_b'
    },
    {
      id: 'cit_spire_monolith',
      name: 'Central Spire Monolith',
      type: 'cube',
      position: [0, 4.5, 0],
      size: [7, 9, 7],
      color: '#0f172a',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 1.0
    },
    {
      id: 'cit_west_wall',
      name: 'West Sector Bulkhead',
      type: 'wall',
      position: [-15, 3.5, 0],
      size: [1.5, 7, 36],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 0.9
    },
    {
      id: 'cit_east_wall',
      name: 'East Sector Bulkhead',
      type: 'wall',
      position: [15, 3.5, 0],
      size: [1.5, 7, 36],
      color: '#334155',
      material: 'concrete',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'mid',
      penetrationResistance: 0.9
    },
    {
      id: 'cit_a_server_1',
      name: 'Quantum Rack Alpha',
      type: 'cube',
      position: [-28, 1.8, -16],
      size: [3.5, 3.6, 5.5],
      color: '#0284c7',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_a',
      penetrationResistance: 0.65
    },
    {
      id: 'cit_b_obelisk',
      name: 'Helipad Beacon Core',
      type: 'cylinder',
      position: [28, 2.0, -16],
      size: [4.0, 4.0, 4.0],
      color: '#f59e0b',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'site_b',
      penetrationResistance: 0.7
    }
  ],
  portals: [],
  waypoints: [
    { id: 'c_s', position: [0, 0, -40], connections: ['c_mid', 'c_a', 'c_b'], tag: 'sentinelSpawn' },
    { id: 'c_v', position: [0, 0, 40], connections: ['c_mid', 'c_a', 'c_b'], tag: 'vortexSpawn' },
    { id: 'c_mid', position: [6, 0, 0], connections: ['c_s', 'c_v'], tag: 'mid' },
    { id: 'c_a', position: [-26, 0, -14], connections: ['c_s', 'c_v'], tag: 'siteA' },
    { id: 'c_b', position: [26, 0, -14], connections: ['c_s', 'c_v'], tag: 'siteB' }
  ],
  callouts: [
    { name: 'Spire Courtyard', position: [0, 0, 0], radius: 15 },
    { name: 'Quantum A', position: [-28, 0, -16], radius: 14 },
    { name: 'Helipad B', position: [28, 0, -16], radius: 14 }
  ]
};

export const FOUNDRY_WING_MAP: GameMapDefinition = {
  id: 'foundry_wing',
  name: 'Foundry Core',
  subtitle: 'Compact 2v2 Smelting Chamber // Wingman & Retakes',
  author: 'Vanguard Studio',
  version: '1.5.0',
  description:
    'High-intensity close-quarters arena built specifically for 2v2 Wingman, Retakes, and fast-paced duels around a single central Crucible objective.',
  supportedModes: ['Wingman', 'Retakes', 'Rush', 'Deathmatch', 'Practice', 'Custom', 'Competitive'],
  ambientColor: '#78716c',
  skyColor: '#1c100b',
  fogColor: '#291711',
  sunDirection: [30, 80, 20],
  bounds: { min: [-40, -2, -40], max: [40, 20, 40] },
  objects: [
    ...createPerimeterWalls(68, 68, 9, '#292524'),
    {
      id: 'fnd_spawn_s',
      name: 'Sentinel Spawn',
      type: 'spawn_sentinel',
      position: [0, 0.1, -26],
      size: [10, 0.2, 6],
      color: '#06b6d4',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'fnd_buy_s',
      name: 'Sentinel Buy Zone',
      type: 'buy_zone',
      position: [0, 1.5, -26],
      size: [12, 3, 8],
      color: '#06b6d4',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'fnd_spawn_v',
      name: 'Vortex Spawn',
      type: 'spawn_vortex',
      position: [0, 0.1, 26],
      size: [10, 0.2, 6],
      color: '#f59e0b',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'fnd_buy_v',
      name: 'Vortex Buy Zone',
      type: 'buy_zone',
      position: [0, 1.5, 26],
      size: [12, 3, 8],
      color: '#f59e0b',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'fnd_site_a',
      name: 'Bomb Site A (Central Crucible)',
      type: 'bomb_site_a',
      position: [0, 0.15, 0],
      size: [14, 0.3, 14],
      color: '#ef4444',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'fnd_crucible',
      name: 'Molten Crucible Vat',
      type: 'cylinder',
      position: [0, 2.0, 0],
      size: [4.5, 4.0, 4.5],
      color: '#ea580c',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'main',
      penetrationResistance: 0.85
    },
    {
      id: 'fnd_wall_w',
      name: 'West Blast Shield',
      type: 'wall',
      position: [-12, 2.5, 0],
      size: [2, 5, 16],
      color: '#44403c',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'main',
      penetrationResistance: 0.8
    },
    {
      id: 'fnd_wall_e',
      name: 'East Blast Shield',
      type: 'wall',
      position: [12, 2.5, 0],
      size: [2, 5, 16],
      color: '#44403c',
      material: 'metal',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'main',
      penetrationResistance: 0.8
    },
    {
      id: 'fnd_cover_nw',
      name: 'NW Ingot Stack',
      type: 'cover',
      position: [-6, 1.0, -9],
      size: [2.5, 2.0, 2.5],
      color: '#d97706',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'near',
      roomId: 'main',
      penetrationResistance: 0.5
    },
    {
      id: 'fnd_cover_se',
      name: 'SE Ingot Stack',
      type: 'cover',
      position: [6, 1.0, 9],
      size: [2.5, 2.0, 2.5],
      color: '#d97706',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'near',
      roomId: 'main',
      penetrationResistance: 0.5
    }
  ],
  portals: [],
  waypoints: [
    { id: 'f_s', position: [0, 0, -24], connections: ['f_w', 'f_e', 'f_c'], tag: 'sentinelSpawn' },
    { id: 'f_v', position: [0, 0, 24], connections: ['f_w', 'f_e', 'f_c'], tag: 'vortexSpawn' },
    { id: 'f_w', position: [-18, 0, 0], connections: ['f_s', 'f_v', 'f_c'], tag: 'cover' },
    { id: 'f_e', position: [18, 0, 0], connections: ['f_s', 'f_v', 'f_c'], tag: 'cover' },
    { id: 'f_c', position: [5, 0, 0], connections: ['f_s', 'f_v', 'f_w', 'f_e'], tag: 'siteA' }
  ],
  callouts: [
    { name: 'Crucible Site', position: [0, 0, 0], radius: 12 },
    { name: 'West Smelter', position: [-18, 0, 0], radius: 10 },
    { name: 'East Smelter', position: [18, 0, 0], radius: 10 }
  ]
};

export const PROVING_GROUNDS_MAP: GameMapDefinition = {
  id: 'proving_grounds',
  name: 'Apex Proving Grounds',
  subtitle: 'Ballistics, Recoil, Movement & Grenade Training Facility',
  author: 'Vanguard Studio',
  version: '3.0.0',
  description:
    'Dedicated competitive training facility with calibrated distance lanes (15m / 30m / 45m), spray pattern feedback wall, KZ movement stairs/ramps, and grenade trajectory targets.',
  supportedModes: ['Practice', 'Deathmatch', 'Custom'],
  ambientColor: '#94a3b8',
  skyColor: '#0f172a',
  fogColor: '#1e293b',
  sunDirection: [50, 100, 50],
  bounds: { min: [-55, -2, -55], max: [55, 25, 55] },
  objects: [
    ...createPerimeterWalls(96, 96, 10, '#1e293b'),
    {
      id: 'pg_spawn_s',
      name: 'Firing Line Spawn',
      type: 'spawn_sentinel',
      position: [0, 0.1, 28],
      size: [16, 0.2, 6],
      color: '#06b6d4',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'pg_spawn_v',
      name: 'Target Range Bot Spawn',
      type: 'spawn_vortex',
      position: [0, 0.1, -18],
      size: [28, 0.2, 16],
      color: '#f59e0b',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'pg_buy_all',
      name: 'Full Range Armory Zone',
      type: 'buy_zone',
      position: [0, 1.5, 28],
      size: [24, 3, 12],
      color: '#10b981',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'pg_recoil_wall',
      name: 'Calibrated Recoil Spray Target Board',
      type: 'wall',
      position: [-24, 2.5, 10],
      size: [8, 5, 0.6],
      color: '#0ea5e9',
      material: 'tile',
      collidable: true,
      occluder: true,
      lodTier: 'always',
      roomId: 'main',
      penetrationResistance: 0.9
    },
    {
      id: 'pg_wallbang_board',
      name: 'Penetration Test Partition (Wood)',
      type: 'cover',
      position: [14, 1.6, 6],
      size: [5, 3.2, 0.4],
      color: '#d97706',
      material: 'wood',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'main',
      penetrationResistance: 0.2
    },
    {
      id: 'pg_kz_ramp_1',
      name: 'Movement Strafe Ramp 1',
      type: 'ramp',
      position: [30, 1.0, 13.5],
      size: [4, 2.4, 6],
      color: '#10b981',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'pg_kz_plat_1',
      name: 'Movement Platform 1',
      type: 'floor',
      position: [30, 2.0, 8],
      size: [4, 0.4, 5],
      color: '#06b6d4',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'pg_kz_plat_2',
      name: 'Movement Bhop Island 2',
      type: 'floor',
      position: [30, 2.4, -1],
      size: [3.5, 0.4, 4],
      color: '#f59e0b',
      material: 'metal',
      collidable: true,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    },
    {
      id: 'pg_site_a',
      name: 'Practice Bomb Site',
      type: 'bomb_site_a',
      position: [-24, 0.15, -24],
      size: [10, 0.3, 10],
      color: '#ef4444',
      material: 'energy',
      collidable: false,
      occluder: false,
      lodTier: 'always',
      roomId: 'main'
    }
  ],
  portals: [],
  waypoints: [
    { id: 'pg_1', position: [-10, 0, -10], connections: ['pg_2', 'pg_3'], tag: 'mid' },
    { id: 'pg_2', position: [0, 0, -20], connections: ['pg_1', 'pg_3'], tag: 'siteA' },
    { id: 'pg_3', position: [10, 0, -12], connections: ['pg_1', 'pg_2'], tag: 'cover' }
  ],
  callouts: [
    { name: 'Firing Line', position: [0, 0, 28], radius: 12 },
    { name: 'Recoil Lab', position: [-24, 0, 15], radius: 10 },
    { name: 'KZ Strafe Course', position: [30, 0, 8], radius: 12 },
    { name: 'Bot Target Pit', position: [0, 0, -18], radius: 16 }
  ]
};

export const OFFICIAL_MAPS: Record<string, GameMapDefinition> = {
  harbor_protocol: HARBOR_PROTOCOL_MAP,
  citadel_spire: CITADEL_SPIRE_MAP,
  foundry_wing: FOUNDRY_WING_MAP,
  proving_grounds: PROVING_GROUNDS_MAP
};

export function getMapById(mapId: string, customMaps: Record<string, GameMapDefinition> = {}): GameMapDefinition {
  return customMaps[mapId] || OFFICIAL_MAPS[mapId] || HARBOR_PROTOCOL_MAP;
}
